### ISSUE TITLE
making tables - pinedit?

### ISSUE THREAD

**Issue by ohnonot** [sergiomb2/pinball.old#2]
Hello,
I was very happy to see something fairly recent happening for emilia pinball, and can now enjoy 3 more tables :-)

how did you (or somebody) make the tables?
i tried to compile pinedit http://sourceforge.net/projects/pinball/files/pinedit/pinedit-0.3.1/ but it failed because it didn't like the qt3 version available on archlinux...

**Comment by sergiomb2** [comment]
Hi, 
I just compiled the sources and patches that were floating on the Internet, I did not develop the code.
I read somewhere what delay have more tables was pinedit that have many bugs .
Anyway you should/may try compile from last git sources: https://sourceforge.net/p/pinball/pinedit/ci/master/tree/

**Comment by sergiomb2** [comment]
I just added https://github.com/sergiomb2/pinball-pinedit , and merge qt4 branch , if you have time you may try it . I will give you more news after try to compile it .

**Comment by ohnonot** [comment]
thanks a lot!
how do i configure/make/install it?
i tried ./bootsrap but still couldn't make afterwards.
./install-sh just says: no input file specified.... ?

**Comment by sergiomb2** [comment]
```
autoreconf -vif
./configure --help
./configure 
make 
make install
```

autoreconf -vif works the rest I don't test it yet

**Comment by sergiomb2** [comment]
you got a new release 
https://github.com/sergiomb2/pinball-pinedit/releases/tag/v0.3.2 
I'm going delete this pinball.old repo , to see if fix some github problems
