### ISSUE TITLE
Unlimited balls mode

### ISSUE THREAD

**Issue by albertaparicio** [sergiomb2/pinball.old#5]
Dear sergiomb2,

I would like to know if there is a way for this great game to have a mode where I can play with an unlimited number of balls, instead of only 3. I have seen this mode in the Android game Vector Pinball, and it is a lot of fun.

If you could implement this mode, it would be a blessing.

Thank you very much

**Comment by sergiomb2** [comment]
moved to https://github.com/sergiomb2/pinball/issues/7
